#!/bin/sh
# Render the deploy configs with a generated RPC password into the shared
# `config` volume. Run automatically by the compose `setup` service before
# bitcoind and the pool start -- you don't invoke this by hand.
#
# Idempotent: the password is generated once (stored in the volume) and reused
# on every later start, so bitcoind and the pool always share matching
# credentials. `docker compose down -v` wipes the volume and, on the next `up`,
# a fresh password is generated.
set -eu

PW_FILE=/config/.rpcpassword

if [ -s "$PW_FILE" ]; then
    PW=$(cat "$PW_FILE")
    echo "setup: reusing the existing RPC password"
else
    PW=$(head -c 64 /dev/urandom | sha256sum | cut -c1-48)
    printf '%s' "$PW" > "$PW_FILE"
    chmod 600 "$PW_FILE"
    echo "setup: generated a new RPC password"
fi

# Substitute the placeholder in every mounted template (hex password => safe
# with a '/' sed delimiter) and write the result into the shared volume.
for tpl in /templates/*; do
    sed "s/CHANGE_ME_before_deploying/$PW/g" "$tpl" > "/config/$(basename "$tpl")"
done

if [ -n "${POOL1_EXTRANONCE1_PREFIX:-}" ] || [ -n "${POOL2_EXTRANONCE1_PREFIX:-}" ]; then
    : "${POOL1_EXTRANONCE1_PREFIX:?POOL1_EXTRANONCE1_PREFIX is required for HA}"
    : "${POOL2_EXTRANONCE1_PREFIX:?POOL2_EXTRANONCE1_PREFIX is required for HA}"
    if grep -Eq '^[[:space:]]*(extranonce1_size|extranonce1_prefix):' /config/pool.yml; then
        echo "setup: HA base pool.yml must not set extranonce1_size or extranonce1_prefix" >&2
        exit 1
    fi
    for replica in 1 2; do
        case "$replica" in
            1) prefix=$POOL1_EXTRANONCE1_PREFIX ;;
            2) prefix=$POOL2_EXTRANONCE1_PREFIX ;;
        esac
        # Size extranonce1 to leave exactly four counter bytes for whatever prefix length is given,
        # and reject a malformed prefix here (with a clear message) instead of letting the pool fail
        # config validation at boot. A 1-4 byte prefix -> extranonce1_size 5-8, always 4 counter bytes.
        case "$prefix" in
            *[!0-9A-Fa-f]*)
                echo "setup: extranonce1 prefix '$prefix' must be hexadecimal" >&2; exit 1 ;;
        esac
        prefix_len=${#prefix}
        if [ $((prefix_len % 2)) -ne 0 ] || [ "$prefix_len" -lt 2 ] || [ "$prefix_len" -gt 8 ]; then
            echo "setup: extranonce1 prefix '$prefix' must be an even 2-8 hex chars (1-4 bytes)" >&2
            exit 1
        fi
        size=$((prefix_len / 2 + 4))
        cp /config/pool.yml "/config/pool${replica}.yml"
        printf '\n# Replica-specific work domain; generated by setup.sh.\nextranonce1_size: %s\nextranonce1_prefix: "%s"\n' \
            "$size" "$prefix" >> "/config/pool${replica}.yml"
    done
fi

echo "setup: rendered $(ls /templates | tr '\n' ' ')-> shared config volume"
