{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "erikslund-pool.fullname" . }}
  labels: {{- include "erikslund-pool.labels" . | nindent 4 }}
spec:
  # Replicas kept serving through voluntary disruptions (drains, upgrades).
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{- include "erikslund-pool.selectorLabels" . | nindent 6 }}
{{- end }}
